# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relay < Formula
  desc "Manage AI agent skills and agents across providers"
  homepage "https://github.com/patrikmichi/relay"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrikmichi/relay/releases/download/v0.2.2/relay-darwin-amd64.tar.gz"
      sha256 "7ba1642b63317138058b2a7862623ccc5667d609f1a97ee6912d52069fce2025"

      define_method(:install) do
        bin.install "relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/patrikmichi/relay/releases/download/v0.2.2/relay-darwin-arm64.tar.gz"
      sha256 "737b9f6c3625424e64b1bba50a3a6404e197b32934522c4248ec2e2e547b186d"

      define_method(:install) do
        bin.install "relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrikmichi/relay/releases/download/v0.2.2/relay-linux-amd64.tar.gz"
      sha256 "b2680801341efa3f1324b53702c398c968ac1e93fc9018fbb223be913e9caca9"
      define_method(:install) do
        bin.install "relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/patrikmichi/relay/releases/download/v0.2.2/relay-linux-arm64.tar.gz"
      sha256 "07d99b930dafc6af9defd6f86ef79160a644868f9fc5f8c3df57063d047721fb"
      define_method(:install) do
        bin.install "relay"
      end
    end
  end

  test do
    system "#{bin}/relay", "--version"
  end
end
